---
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi-test
spec:
  runtimeClassName: nvidia
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:12.2.2-base-ubuntu22.04
      command: ["/bin/bash", "-c", "--"]
      args: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 2 # We use more than 1 part to ensure the time slicing in configured
  restartPolicy: Never